name: Flutter CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.41.1" # Sesuaikan dengan versi Flutter yang lo pakai sekarang
          channel: "stable"

      - name: Install Dependencies
        uses: subosito/flutter-action@v2 # Opsional, atau langsung pakai flutter pub get
        run: flutter pub get

      - name: Analyze Code
        run: flutter analyze

      - name: Run Tests
        run: flutter test
